// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Client2Server.proto

#include "Client2Server.pb.h"
#include "Client2Server.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Client2Server {

static const char* CSGreeter_method_names[] = {
  "/Client2Server.CSGreeter/CSCommunication",
};

std::unique_ptr< CSGreeter::Stub> CSGreeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CSGreeter::Stub> stub(new CSGreeter::Stub(channel, options));
  return stub;
}

CSGreeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CSCommunication_(CSGreeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CSGreeter::Stub::CSCommunication(::grpc::ClientContext* context, const ::Client2Server::CSRequest& request, ::Client2Server::CSReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Client2Server::CSRequest, ::Client2Server::CSReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CSCommunication_, context, request, response);
}

void CSGreeter::Stub::async::CSCommunication(::grpc::ClientContext* context, const ::Client2Server::CSRequest* request, ::Client2Server::CSReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Client2Server::CSRequest, ::Client2Server::CSReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CSCommunication_, context, request, response, std::move(f));
}

void CSGreeter::Stub::async::CSCommunication(::grpc::ClientContext* context, const ::Client2Server::CSRequest* request, ::Client2Server::CSReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CSCommunication_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Client2Server::CSReply>* CSGreeter::Stub::PrepareAsyncCSCommunicationRaw(::grpc::ClientContext* context, const ::Client2Server::CSRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Client2Server::CSReply, ::Client2Server::CSRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CSCommunication_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Client2Server::CSReply>* CSGreeter::Stub::AsyncCSCommunicationRaw(::grpc::ClientContext* context, const ::Client2Server::CSRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCSCommunicationRaw(context, request, cq);
  result->StartCall();
  return result;
}

CSGreeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CSGreeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CSGreeter::Service, ::Client2Server::CSRequest, ::Client2Server::CSReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CSGreeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Client2Server::CSRequest* req,
             ::Client2Server::CSReply* resp) {
               return service->CSCommunication(ctx, req, resp);
             }, this)));
}

CSGreeter::Service::~Service() {
}

::grpc::Status CSGreeter::Service::CSCommunication(::grpc::ServerContext* context, const ::Client2Server::CSRequest* request, ::Client2Server::CSReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Client2Server

