// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server2Verifier.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Server2Verifier_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Server2Verifier_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Server2Verifier_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Server2Verifier_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Server2Verifier_2eproto;
namespace Server2Verifier {
class SVReply;
struct SVReplyDefaultTypeInternal;
extern SVReplyDefaultTypeInternal _SVReply_default_instance_;
class SVRequest;
struct SVRequestDefaultTypeInternal;
extern SVRequestDefaultTypeInternal _SVRequest_default_instance_;
}  // namespace Server2Verifier
PROTOBUF_NAMESPACE_OPEN
template<> ::Server2Verifier::SVReply* Arena::CreateMaybeMessage<::Server2Verifier::SVReply>(Arena*);
template<> ::Server2Verifier::SVRequest* Arena::CreateMaybeMessage<::Server2Verifier::SVRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Server2Verifier {

// ===================================================================

class SVRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Server2Verifier.SVRequest) */ {
 public:
  inline SVRequest() : SVRequest(nullptr) {}
  ~SVRequest() override;
  explicit PROTOBUF_CONSTEXPR SVRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SVRequest(const SVRequest& from);
  SVRequest(SVRequest&& from) noexcept
    : SVRequest() {
    *this = ::std::move(from);
  }

  inline SVRequest& operator=(const SVRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SVRequest& operator=(SVRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SVRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SVRequest* internal_default_instance() {
    return reinterpret_cast<const SVRequest*>(
               &_SVRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SVRequest& a, SVRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SVRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SVRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SVRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SVRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SVRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SVRequest& from) {
    SVRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SVRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Server2Verifier.SVRequest";
  }
  protected:
  explicit SVRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHFieldNumber = 1,
    kRandhFieldNumber = 2,
  };
  // string h = 1;
  void clear_h();
  const std::string& h() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_h(ArgT0&& arg0, ArgT... args);
  std::string* mutable_h();
  PROTOBUF_NODISCARD std::string* release_h();
  void set_allocated_h(std::string* h);
  private:
  const std::string& _internal_h() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_h(const std::string& value);
  std::string* _internal_mutable_h();
  public:

  // string randh = 2;
  void clear_randh();
  const std::string& randh() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_randh(ArgT0&& arg0, ArgT... args);
  std::string* mutable_randh();
  PROTOBUF_NODISCARD std::string* release_randh();
  void set_allocated_randh(std::string* randh);
  private:
  const std::string& _internal_randh() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_randh(const std::string& value);
  std::string* _internal_mutable_randh();
  public:

  // @@protoc_insertion_point(class_scope:Server2Verifier.SVRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr h_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr randh_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Server2Verifier_2eproto;
};
// -------------------------------------------------------------------

class SVReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Server2Verifier.SVReply) */ {
 public:
  inline SVReply() : SVReply(nullptr) {}
  ~SVReply() override;
  explicit PROTOBUF_CONSTEXPR SVReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SVReply(const SVReply& from);
  SVReply(SVReply&& from) noexcept
    : SVReply() {
    *this = ::std::move(from);
  }

  inline SVReply& operator=(const SVReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline SVReply& operator=(SVReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SVReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const SVReply* internal_default_instance() {
    return reinterpret_cast<const SVReply*>(
               &_SVReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SVReply& a, SVReply& b) {
    a.Swap(&b);
  }
  inline void Swap(SVReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SVReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SVReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SVReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SVReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SVReply& from) {
    SVReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SVReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Server2Verifier.SVReply";
  }
  protected:
  explicit SVReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:Server2Verifier.SVReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Server2Verifier_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SVRequest

// string h = 1;
inline void SVRequest::clear_h() {
  _impl_.h_.ClearToEmpty();
}
inline const std::string& SVRequest::h() const {
  // @@protoc_insertion_point(field_get:Server2Verifier.SVRequest.h)
  return _internal_h();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SVRequest::set_h(ArgT0&& arg0, ArgT... args) {
 
 _impl_.h_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Server2Verifier.SVRequest.h)
}
inline std::string* SVRequest::mutable_h() {
  std::string* _s = _internal_mutable_h();
  // @@protoc_insertion_point(field_mutable:Server2Verifier.SVRequest.h)
  return _s;
}
inline const std::string& SVRequest::_internal_h() const {
  return _impl_.h_.Get();
}
inline void SVRequest::_internal_set_h(const std::string& value) {
  
  _impl_.h_.Set(value, GetArenaForAllocation());
}
inline std::string* SVRequest::_internal_mutable_h() {
  
  return _impl_.h_.Mutable(GetArenaForAllocation());
}
inline std::string* SVRequest::release_h() {
  // @@protoc_insertion_point(field_release:Server2Verifier.SVRequest.h)
  return _impl_.h_.Release();
}
inline void SVRequest::set_allocated_h(std::string* h) {
  if (h != nullptr) {
    
  } else {
    
  }
  _impl_.h_.SetAllocated(h, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.h_.IsDefault()) {
    _impl_.h_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Server2Verifier.SVRequest.h)
}

// string randh = 2;
inline void SVRequest::clear_randh() {
  _impl_.randh_.ClearToEmpty();
}
inline const std::string& SVRequest::randh() const {
  // @@protoc_insertion_point(field_get:Server2Verifier.SVRequest.randh)
  return _internal_randh();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SVRequest::set_randh(ArgT0&& arg0, ArgT... args) {
 
 _impl_.randh_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Server2Verifier.SVRequest.randh)
}
inline std::string* SVRequest::mutable_randh() {
  std::string* _s = _internal_mutable_randh();
  // @@protoc_insertion_point(field_mutable:Server2Verifier.SVRequest.randh)
  return _s;
}
inline const std::string& SVRequest::_internal_randh() const {
  return _impl_.randh_.Get();
}
inline void SVRequest::_internal_set_randh(const std::string& value) {
  
  _impl_.randh_.Set(value, GetArenaForAllocation());
}
inline std::string* SVRequest::_internal_mutable_randh() {
  
  return _impl_.randh_.Mutable(GetArenaForAllocation());
}
inline std::string* SVRequest::release_randh() {
  // @@protoc_insertion_point(field_release:Server2Verifier.SVRequest.randh)
  return _impl_.randh_.Release();
}
inline void SVRequest::set_allocated_randh(std::string* randh) {
  if (randh != nullptr) {
    
  } else {
    
  }
  _impl_.randh_.SetAllocated(randh, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.randh_.IsDefault()) {
    _impl_.randh_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Server2Verifier.SVRequest.randh)
}

// -------------------------------------------------------------------

// SVReply

// string message = 1;
inline void SVReply::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& SVReply::message() const {
  // @@protoc_insertion_point(field_get:Server2Verifier.SVReply.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SVReply::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Server2Verifier.SVReply.message)
}
inline std::string* SVReply::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:Server2Verifier.SVReply.message)
  return _s;
}
inline const std::string& SVReply::_internal_message() const {
  return _impl_.message_.Get();
}
inline void SVReply::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* SVReply::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* SVReply::release_message() {
  // @@protoc_insertion_point(field_release:Server2Verifier.SVReply.message)
  return _impl_.message_.Release();
}
inline void SVReply::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Server2Verifier.SVReply.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Server2Verifier

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Server2Verifier_2eproto
